[build]
  publish = ".next"
  command = "npm run build"

[[plugins]]
  package = "@netlify/plugin-csp-nonce"
  [plugins.inputs]
      excludedPath = [
      "/_next/image*",
      "/_next/static*",
      "/api/**/*",
      "/**/*?_rsc=*"
    ]